name: Trigger auto deployment for fyt-frontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/fyt-frontend-AutoDeployTrigger-76c1f0e3-950f-4e1c-bc20-b3dea7d9d77d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FYTFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FYTFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FYTFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: fillyourtoteregistry-cvbsh0b6bwbhhefn.azurecr.io
          registryUsername: ${{ secrets.FYTFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FYTFRONTEND_REGISTRY_PASSWORD }}
          containerAppName: fyt-frontend
          resourceGroup: fillyourtote-resources
          imageToBuild: fillyourtoteregistry-cvbsh0b6bwbhhefn.azurecr.io/fyt-frontend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


